config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root    'tweets#index'                    #ルートパスの指定
  resources :tweets do                         #tweets_controllerに対してのresourcesメソッド
    resources :comments, only: [:create]
  end
  resources :users, only: [:show]           #users_controllerに対してのresourcesメソッド
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tweet               #tweetsテーブルとのアソシエーション
  belongs_to :user                #usersテーブルとのアソシエーション
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :comments               #commentsテーブルとのアソシエーション
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :comments               #commentsテーブルとのアソシエーション
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    redirect_to "/tweets/#{@comment.tweet.id}"          #コメントと結びつくツイートの詳細画面に遷移する
  end

  private
  def comment_params
    params.permit(:text, :tweet_id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :move_to_index, except: [:index, :show]

  def index
    @tweets = Tweet.includes(:user).page(params[:page]).per(10).order("created_at DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(text: tweet_params[:text], user_id: current_user.id)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.destroy
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

    def update
      tweet = Tweet.find(params[:id])
      if tweet.user_id == current_user.id
        tweet.update(tweet_params)
      end
    end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = current_user.nickname
    @tweets = user.tweets.page(params[:page]).per(10).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Miniapp</title>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="##84ffff cyan accent-1 ">
  <div class="nav-wrapper">
    <a href="/"><span class="center brand-logo">Blog</span></a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <div class="grid-6"><a href="/"></a></h1>
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
            <ul class="user__info">
                <li><a href="/users/<%= current_user.id %>"><%= current_user.nickname %></a></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                <li><a class="post" href="/tweets/new">New</a></li>
            </ul>
          </span>
        </div>
      <% else %>
        <div class="grid-6">
          <li><%= link_to "Login", new_user_session_path, class: 'post' %></li>
          <li><%= link_to "Registration", new_user_registration_path, class: 'post' %></li>
        </div>
      <% end %>
    </ul>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/tweets/_tweet.html.erb
    <a href="/users/<%= tweet.user_id %>">
      <span>投稿者</span> <%= tweet.user.nickname %>
    </a>
  <%= simple_format(tweet.text) %>
    <ul class="list"><br />
      <li class="list1">
        <%= link_to "SHOW", tweet_path(tweet.id), method: :get %>
      </li>
      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li class="list2">
          <%= link_to 'EDIT', "/tweets/#{tweet.id}/edit", method: :get %>
        </li>
        <li class="list3">
          <%= link_to 'DESTROY', "/tweets/#{tweet.id}", method: :delete %>
        </li>
      <% end %>
    </ul><br /><br />

app/views/tweets/create.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
      <a class="btn" href="/tweets">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/tweets/destroy.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/tweets/edit.html.erb
  <div class="contents row">
    <%= form_for(@tweet) do |f| %>
      <h3>
        EDIT
      </h3>
      <%= f.text_area :text, placeholder: "text", style: "height: 200px;" %>
      <input type="submit" value="送信">
    <% end %>
  </div>

app/views/tweets/index.html.erb
<div class="contents row" >
  <% @tweets.each do |tweet| %>
  <div class="box">
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  </div>
  <% end %>
  <%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <%= form_for(@tweet) do |f| %>
    <h3>
      本文
    </h3>
    <%= f.text_area :text, placeholder: "text", style: "height: 200px;" %>
    <input type="submit" value="送信" >
  <% end %>
</div>

app/views/tweets/show.html.erb
<div class ="contents row">
    <span class="name">
      <a href="/users/<%= @tweet.user.id %>">
        <span>投稿者</span><%= @tweet.user.nickname %>
      </a>
    </span>
    <%= simple_format(@tweet.text) %>
</div>
  <div class="container">
    <!-- ここからフォーム -->
      <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %>
        <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
        <input type="submit" value="SENT">
        <% if user_signed_in? && current_user.id == @tweet.user_id %>
        <ul class="more_list_2">
        <li class="list2">
          <%= link_to 'EDIT', "/tweets/#{@tweet.id}/edit", method: :get %>
        </li>
        <li class="list3">
          <%= link_to 'DESTROY', "/tweets/#{@tweet.id}", method: :delete %>
        </li>
        </ul>
      <% end %>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/update.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        更新が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/users/show.html.erb
  <div class="contents row" >
    <p><%= @nickname %>さんの投稿一覧</p>
    <% @tweets.each do |tweet| %>
    <div class="box">
      <%= render partial: "tweets/tweet", locals: { tweet: tweet } %>
    </div>
    <% end %>
    <%= paginate(@tweets) %>
  </div>